@local=http://localhost:5001

GET  {{local}}/api/questionnaire

###

POST  {{local}}/api/questionnaire
Content-Type: application/json


{
     "fullName" : "שלום",
    "bizSize" : "12",
    "seats" : "1200",
    "servingFood" : true,
    "gas" : true
}