@local=http://localhost:5001

GET  {{local}}/api/questionnaire

###

POST  {{local}}/api/questionnaire
Content-Type: application/json


{
  "fullName": "Test Biz",
  "bizSize": 120,
  "seats": 150,
  "alcohol": false,
  "servingFood": true,
  "gas": true
}